version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Initializing environment
      # ✅ Authenticate with AWS CodeArtifact properly
      - aws codeartifact login --tool mvn --repository awqef-repo --domain awqef --domain-owner 724772089053
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no
